// Archivo de base de datos de productos FerFix
export const productsData = [
  // --- CIRCUITOS INTEGRADOS Y FPC ---
  { id: "ci-1", name: "PM670 001L", price: 18000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "IC de gestión de energía (PMIC)." },
  { id: "ci-2", name: "OVP HY HYXX 20P", price: 10000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Protector de sobrevoltaje 20 pines." },
  { id: "ci-3", name: "OVP GF 12P", price: 10000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Protector de sobrevoltaje 12 pines." },
  { id: "ci-4", name: "OVP GQ 12P", price: 10000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Protector de sobrevoltaje 12 pines." },
  { id: "ci-5", name: "OVP HC HCXX 12P", price: 10000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Protector de sobrevoltaje 12 pines." },
  { id: "ci-6", name: "OVP JJ 12P", price: 10000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Protector de sobrevoltaje 12 pines." },
  { id: "ci-7", name: "OVP F9 F9XX 15P", price: 10000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Protector de sobrevoltaje 15 pines." },
  { id: "ci-8", name: "OVP GX GXxx 15P", price: 10000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Protector de sobrevoltaje 15 pines." },
  { id: "ci-9", name: "OVP 1J 1Jx 15P", price: 18000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Protector de sobrevoltaje alta gama." },
  { id: "ci-10", name: "OVP 57=4J", price: 18000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Protector de sobrevoltaje IC." },
  { id: "ci-11", name: "HYxxx LIGHT control IC", price: 10000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Controlador de iluminación." },
  { id: "ci-12", name: "ASL01", price: 20000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Circuito Integrado ASL01." },
  { id: "ci-13", name: "MT6365VPW ORIGINAL", price: 40000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Power Management MediaTek Original." },
  { id: "ci-14", name: "MT6359VMP", price: 20000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "IC Power Management." },
  { id: "ci-15", name: "SM5602 IC Ori", price: 14000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "IC de carga original." },
  { id: "ci-16", name: "338S00739 Audio IC IP13/14", price: 16000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Codec de Audio iPhone 13/14." },
  { id: "ci-17", name: "338S00537 Audio IC IP13", price: 11000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Codec de Audio iPhone 13." },
  { id: "ci-18", name: "SN2012027/8N Eeprom Charging IP16", price: 30000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Eeprom de carga iPhone 16." },
  { id: "ci-19", name: "STB605A11 Power Management IP16 /15", price: 24000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "PMIC iPhone 15/16." },
  { id: "ci-20", name: "338S00843 Audio IC IP/16/15 ori", price: 16000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Codec Audio iPhone 15/16 Original." },
  { id: "ci-21", name: "Q4EE IC IP16/15", price: 17000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "IC para serie iPhone 15/16." },
  { id: "ci-22", name: "338S00616 Backlight IC IP13/12", price: 11000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "IC de Retroiluminación." },
  { id: "ci-23", name: "SDR735 Radio Frequency IC", price: 11000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "IC de Radiofrecuencia." },
  { id: "ci-24", name: "SN2501A1 Charging ic IP8/SE", price: 6000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "IC de carga iPhone 8/SE." },
  { id: "ci-25", name: "malla de parlante IP16/16pm", price: 5500, category: "Circuitos Integrados", image_url: "/productos/acc.jpg", description: "Repuesto malla parlante." },
  { id: "fpc-1", name: "FPC Parlante onboard IP14 ori 22pin", price: 5500, category: "Circuitos Integrados", image_url: "/productos/fpc.jpg", description: "FPC Parlante iPhone 14." },
  { id: "fpc-2", name: "FPC USB onboard IP14/14P 28pin", price: 5500, category: "Circuitos Integrados", image_url: "/productos/fpc.jpg", description: "FPC USB iPhone 14/14P." },
  { id: "fpc-3", name: "FPC USB onboard IP13 44pin", price: 5500, category: "Circuitos Integrados", image_url: "/productos/fpc.jpg", description: "FPC USB iPhone 13." },
  { id: "fpc-4", name: "FPC Battery onboard IP13/13P/13PM/14/14P ori 8pin", price: 5500, category: "Circuitos Integrados", image_url: "/productos/fpc.jpg", description: "FPC Batería iPhone 13/14." },
  { id: "fpc-5", name: "FPC LCD onboard ip12/12p 34pin", price: 5500, category: "Circuitos Integrados", image_url: "/productos/fpc.jpg", description: "FPC Pantalla iPhone 12." },
  { id: "fpc-6", name: "FPC Battery onboard ip12/12p/12pm ori 8pin", price: 5500, category: "Circuitos Integrados", image_url: "/productos/fpc.jpg", description: "FPC Batería iPhone 12." },
  { id: "fpc-7", name: "FPC Camara trasera onboard ip12/12p 26 pin", price: 5500, category: "Circuitos Integrados", image_url: "/productos/fpc.jpg", description: "FPC Cámara iPhone 12." },
  { id: "fpc-8", name: "FPC LCD onboard ip11p/11pm 36pin", price: 5500, category: "Circuitos Integrados", image_url: "/productos/fpc.jpg", description: "FPC Pantalla iPhone 11 Pro." },
  { id: "fpc-9", name: "FPC Touch onboard ip11/11p/11pm 20pin", price: 5500, category: "Circuitos Integrados", image_url: "/productos/fpc.jpg", description: "FPC Touch iPhone 11." },
  { id: "fpc-10", name: "FPC USB on board ip11 34pin", price: 5500, category: "Circuitos Integrados", image_url: "/productos/fpc.jpg", description: "FPC USB iPhone 11." },
  { id: "fpc-11", name: "FPC Touch onboard ip12/12p 18pin", price: 5500, category: "Circuitos Integrados", image_url: "/productos/fpc.jpg", description: "FPC Touch iPhone 12." },
  { id: "ci-26", name: "SPS25 ic Power samg Ultra 5g ori", price: 33000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "IC Power Samsung Ultra Original." },
  { id: "ci-27", name: "SM5451 ic charging", price: 17000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "IC Carga Samsung." },
  { id: "ci-28", name: "PM6350 ic Power sam gal a53 5g", price: 23000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "IC Power Samsung A53 5G." },
  { id: "ci-29", name: "SGM41511 ic charging", price: 7500, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "IC Carga SGM." },
  { id: "ci-30", name: "SGM3838YG IC", price: 17000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Circuito Integrado SGM." },
  { id: "ci-31", name: "SM5450", price: 14000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "IC SM5450." },
  { id: "ci-32", name: "PM7325", price: 16000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "IC Power PM7325." },
  { id: "ci-33", name: "UCCMAD PMIC ori", price: 14500, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "PMIC Original UCCMAD." },
  { id: "fpc-12", name: "FPC 8P Flex Sam A32", price: 2800, category: "Circuitos Integrados", image_url: "/productos/fpc.jpg", description: "FPC Flex Samsung A32." },
  { id: "fpc-13", name: "FPC 8P Board Sam A32", price: 2800, category: "Circuitos Integrados", image_url: "/productos/fpc.jpg", description: "FPC Placa Samsung A32." },
  { id: "fpc-14", name: "FPC 78P Board Sam A13", price: 2800, category: "Circuitos Integrados", image_url: "/productos/fpc.jpg", description: "FPC Placa Samsung A13." },
  { id: "fpc-15", name: "FPC 48P Sam A13 Board", price: 2800, category: "Circuitos Integrados", image_url: "/productos/fpc.jpg", description: "FPC Placa Samsung A13 48P." },
  { id: "ci-34", name: "Diodo D4", price: 8000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Diodo de protección D4." },
  { id: "ci-35", name: "KTS1682EAY OVP", price: 10000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "OVP KTS1682EAY." },
  { id: "ci-36", name: "SPU15Q IC Sam A54 5G", price: 45000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "IC Samsung A54 5G." },
  { id: "ci-37", name: "SPU16 IC Power", price: 36000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "IC Power SPU16." },
  { id: "ci-38", name: "SN61280H IC Power", price: 22000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "IC Power SN61280H." },
  { id: "ci-39", name: "MMSZ4690T1G", price: 2000, category: "Circuitos Integrados", image_url: "/productos/ic.jpg", description: "Diodo Zener." },

  // --- HERRAMIENTAS, INSUMOS Y ACCESORIOS ---
  { id: "h-1", name: "Cajas organizadoras celulares", price: 12000, category: "Herramientas e Insumos", image_url: "/productos/tool.jpg", description: "Organizador para tornillos y partes." },
  { id: "h-2", name: "Aritos magneticos destonillador x10", price: 10000, category: "Herramientas e Insumos", image_url: "/productos/tool.jpg", description: "Magnetizadores para puntas." },
  { id: "h-3", name: "Hoja de cobre disipadora 0.3mm x100", price: 42000, category: "Herramientas e Insumos", image_url: "/productos/tool.jpg", description: "Disipadores térmicos de cobre." },
  { id: "h-4", name: "Tester de Bobiba Lanrui MaAnt", price: 20000, category: "Herramientas e Insumos", image_url: "/productos/tool.jpg", description: "Herramienta de diagnóstico." },
  { id: "h-5", name: "Cable USB-C 6A carga rápida resorte", price: 15000, category: "Herramientas e Insumos", image_url: "/productos/acc.jpg", description: "Cable de alta velocidad." },
  { id: "h-6", name: "Herramientas Extractor SIM x10", price: 4200, category: "Herramientas e Insumos", image_url: "/productos/tool.jpg", description: "Llaves extractoras SIM." },
  { id: "h-7", name: "Cable USB Carplay", price: 22000, category: "Herramientas e Insumos", image_url: "/productos/acc.jpg", description: "Cable certificado CarPlay." },
  { id: "h-8", name: "Kit LANRUI U8 saca tornillos iphone", price: 32000, category: "Herramientas e Insumos", image_url: "/productos/tool.jpg", description: "Kit para tornillos barridos." },
  { id: "h-9", name: "Cinta de niquel para 18650 10M", price: 24000, category: "Herramientas e Insumos", image_url: "/productos/tool.jpg", description: "Para soldadura de puntos en baterías." },
  { id: "h-10", name: "Funda MagSafe Ip17/17p/17pm/17Air", price: 14000, category: "Herramientas e Insumos", image_url: "/productos/case.jpg", description: "Funda MagSafe alta calidad." },
  { id: "h-11", name: "2UUL SC10 Fever Thermal Paste 50G", price: 20000, category: "Herramientas e Insumos", image_url: "/productos/tool.jpg", description: "Pasta térmica profesional." },
  { id: "h-12", name: "Flux YCS Number One No-clean", price: 23500, category: "Herramientas e Insumos", image_url: "/productos/tool.jpg", description: "Flux premium no-clean." },
  { id: "h-13", name: "2UUL LQ conductive ink LCD FIX", price: 60000, category: "Herramientas e Insumos", image_url: "/productos/tool.jpg", description: "Tinta conductiva para reparación LCD." },

  // --- RESISTENCIAS SMD X 10 (Todas a $5000) ---
  ...[
    "Res 2.2k 15v 0201", "Res 0 25v 0201", "Res 1k 25v 0201", "Res 1M 25v 0201", "Res 2k 25v 0201",
    "Res 1.5k 25v 0201", "Res 10k 25v 0201", "Res 4.7k 25v 0201", "Res 22k 30v 0201", "Res 30k 25v 0201",
    "Res 47k 25v 0201", "Res 150k 25v 0201", "Res 0 50v 0402", "Res 1k 50v 0402", "Res 1M 50v 0402",
    "Res 2.2k 50v 0402", "Res 3.3k 50v 0402", "Res 10k 50v 0402", "Res 4.7k 50v 0402", "Res 100k 50v 0402",
    "Res 200k 50v 0402", "Res 0 75v 0603", "Res 1k 75v 0603", "Res 1M 75v 0603", "Res 2.2k 75v 0603",
    "Res 3.3k 75v 0603", "Res 10k 75v 0603", "Res 4.7k 75v 0603", "Res 470 25v 0201", "Res 47k 75v 0603",
    "Res 100k 75v 0603", "Res 0 150v 0805", "Res 330 75v 0603", "Res 0 15v 01005", "Res 470k 75v 0603"
  ].map((name, index) => ({
    id: `res-list-${index}`,
    name,
    price: 5000,
    category: "Resistencias SMD",
    image_url: "/productos/res.jpg",
    description: "Pack de 10 unidades de resistencias SMD."
  })),

  // --- CAPACITORES SMD X 10 (Todas a $5000) ---
  ...[
    "Cap 0,47uF 6,3V 01005", "Cap 100nf 25v 0201", "Cap 100nF 6,3V 01005", "Cap 10nf 25v x7R 0201",
    "Cap 10nF 6,3V 01005", "Cap 1nf 25v 0201", "Cap 1uf 16v 0201", "Cap 2.2uf 10v 0201",
    "Cap 220nf 25v 0201", "Cap 220pF 10V 01005", "Cap 22pf 25v 0201", "Cap 330pF 10V 01005",
    "Cap 4.7nf 16v 0201", "Cap 470nF 6,3V 01005", "Cap 470pF 16V 01005", "Cap 100nf 10v 01005",
    "Cap 100pf 16v 01005", "Cap 10uF 25V 0805", "Cap 1uF 50V 0805", "Cap 100nF 50v 0805",
    "Cap 22uF 25V 0805", "Cap 47uF 10V 0805", "Cap 10uF 10V 0603", "Cap 1uF 50V 0603",
    "Cap 10nF 50V 0603", "Cap 22uF 6,3V 0603", "Cap 4,7uF 10V 0603", "Cap 1uF 10V 0402",
    "Cap 10uF 6,3V 0402", "Cap 4,7uF 10V 0402"
  ].map((name, index) => ({
    id: `cap-list-${index}`,
    name,
    price: 5000,
    category: "Capacitores SMD",
    image_url: "/productos/cap.jpg",
    description: "Pack de 10 unidades de capacitores SMD."
  }))
];
   
